# Generated by Django 2.2 on 2019-04-04 01:24

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('food_poll', '0002_auto_20190404_0404'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='body',
            field=jsonfield.fields.JSONField(default={}),
        ),
    ]
