# Generated by Django 2.2 on 2019-04-04 01:37

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('food_poll', '0003_menu_body'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='body',
        ),
        migrations.AlterField(
            model_name='menu',
            name='menu_items',
            field=jsonfield.fields.JSONField(default={}),
        ),
    ]
