# Generated by Django 2.2 on 2019-04-06 23:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('food_poll', '0006_menu_votes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='votes',
        ),
        migrations.CreateModel(
            name='MenuVotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food_poll.Menu')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Menu', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('menu', 'user')},
            },
        ),
    ]
