# Generated by Django 2.2 on 2019-04-06 23:43

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('food_poll', '0008_auto_20190407_0234'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MenuVotes',
            new_name='MenuVote',
        ),
    ]
