# Generated by Django 2.2 on 2019-04-07 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food_poll', '0012_auto_20190407_1454'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='num_vote_down',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='num_vote_up',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='vote_score',
        ),
    ]
