# Generated by Django 2.2 on 2019-04-07 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food_poll', '0014_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='employee',
            new_name='employer',
        ),
        migrations.AlterField(
            model_name='menuvote',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menuvotes', to='food_poll.Profile'),
        ),
    ]
