# Generated by Django 2.2 on 2019-04-07 21:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food_poll', '0016_auto_20190407_2335'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='employer',
            new_name='employee',
        ),
        migrations.AlterField(
            model_name='menuvote',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menuvotes', to=settings.AUTH_USER_MODEL),
        ),
    ]
