# Generated by Django 2.2 on 2019-04-07 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_poll', '0017_auto_20190408_0052'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='restaurant',
        ),
        migrations.AddField(
            model_name='profile',
            name='restaurant',
            field=models.ManyToManyField(blank=True, null=True, to='food_poll.Restaurant'),
        ),
    ]
