# Generated by Django 2.2 on 2019-04-14 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_poll', '0018_auto_20190408_0101'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='restaurant',
            new_name='restaurants',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='menu_items',
        ),
        migrations.AddField(
            model_name='menu',
            name='description',
            field=models.TextField(default='', max_length=5000),
            preserve_default=False,
        ),
    ]
